config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resource :profile, only: [:show, :edit, :update, :post] do
    resources :users, only: [:edit, :update]
  end

  resources :projects, only: [:index, :create, :show, :new, :edit, :update, :destroy] do
    resources :tasks, only: [:create, :new]
  end

  resources :tasks, only: [:show, :edit, :update, :post, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks

  has_many :user_projects
  has_many :users, through: :user_projects
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :users, through: :project
  has_one :task_user, through: :project, source: :users, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one_attached :avatar, optionnal: true
  has_many :user_projects
  has_many :projects, through: :user_projects
  # validation #
  validates :first_name, :last_name, presence: true
  has_many :tasks_as_task_user, through: :project, source: :tasks, class_name: "Task"

end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @user = current_user
    @users = @project.users
    @tasks = @project.tasks
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(projects_params)
    if @project.save
      redirect_to project_path(@project)
    else

      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path(), status: :see_other
  end


  private

  def projects_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.new(tasks_params)
    @task.project = @project
    @task.status = "pending"
    if @task.save
      redirect_to project_path(@project)
    else

      render :new, status: :unprocessable_entity
    end
  end

  def update
    @task = Task.find(params[:id])  # Assuming the user ID is passed as a parameter
    @project = Project.find(params[:project_id])
    if @task.update(task_params)
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @project = Project.find(params[:project_id])
    redirect_to project_path(@project), status: :see_other
  end


  private

  def tasks_params
    params.require(:task).permit(:title, :description, :limit_date, :project_id, :status)
  end
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestionApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Inter:wght@900&family=Jomhuria&family=Rubik:ital,wght@0,300;1,300;1,400&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/projects/index.html.erb
<div class="container">
  <div>
    <h1>Projects </h1>
  </div>
  <div class="col container-contracts mt-4">
    <%@projects.each do |project| %>
      <div class="card" style="width: 400px;">
      <%= link_to project_path(project), style:"text-decoration: none" do%>
          <h2>  <%= link_to project.name, project_path(project), class: "", style:"text-decoration: none" %></h2>
          <p>Description : <%= project.description %></p>
      <% end %>
      </div>
    <%= link_to "Delete",
      project_path(project),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
    <% end %>
  </div>
    <%= link_to "Create a new project", new_project_path(),  class: "btn primary", data: { turbo: false }%>
</div>

app/views/projects/new.html.erb
<div class="banner-creation-band">
  <%= simple_form_for(@project) do |f| %>

      <%# name %>
        <%= f.input :name, label: "name",label_html: { style: "text-shadow: 0px 2px 3px black;" }, placeholder: "project name"%>

      <%# description %>
        <%= f.input :description, label: "Description",label_html: { style: "text-shadow: 0px 2px 3px black;" }, placeholder: "enter the description"%>

      <%= f.button :submit, "Create the project", label: "new project", placeholder: "new project", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div>
  <%= render "shared/back_button" %>
  <div class= "container pt-4">
    <div>
      <h1 class="title-page"><%= @project.name %></h1>
    </div>
    <div>
      <% @tasks.each do |task| %>
        <div class="d-flex task-container justify-content-between">
          <div>
            <h3 class="task-title"> <%= task.title %></h3>
            <p class="task-description"> <%= task.description %> </p>
          </div>
          <div class="d-flex date-status justify-content-around">
            <p class="deadline"> <%= task.limit_date %> </p>
            <% if  task.status == "pending" %>
              <div class="d-flex justify-content-around status-button">
                <%= simple_form_for (task), method: :update do |f| %>
                  <%= f.input :status, label: false, input_html: {value: 'in progress', class:"d-none", }%>
                  <%= f.button :submit, "Take it", class: "btn btn-info" %>
                <% end %>
              </div>
            <%elsif task.status == "in progress" && task.task_user.id != current_user.id %>
              <div class="d-flex justify-content-around text-info status-button">In progress</div>
            <% elsif task.status == "in progress" && task.task_user.id == current_user.id %>
              <div class="d-flex justify-content-around status-button">
                <%= simple_form_for (task) do |f| %>
                  <%= f.input :status, label: false, input_html: {value: 'done', class:"d-none", }%>
                  <%= f.button :submit, "done ?", class: "btn btn-info btn-done" %>
                <% end %>
              </div>
            <%elsif task.status == "done" %>
              <div class="d-flex justify-content-around text-success status-button">Done</div>
            <% end %>
            <%= link_to "Delete",
              task_path(task),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %>
          </div>
        </div>
        <%end%>
    </div>
    <div class="mt-5">
    <%= link_to "New task",  new_project_task_path(@project),  class: "button-task ", data: { turbo: false }%>
    </div>
  </div>
  <div>
  </div>
</div>

app/views/shared/_back_button.html.erb
  <a class="back-btn" href="javascript:history.back()"><strong><i class="fa-solid fa-arrow-left"></i></strong></a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="banner-creation-band">
  <%= simple_form_for [@project, @task] do |f| %>
    <%= f.input :limit_date, html5: true, label: 'dead line:' %>
    <%= f.input :title, label: "title"%>
    <%= f.input :description, label: "description"%>
    <%= f.button :submit, "Create a task", class: "btn btn-info" %>
    <%end%>
</div>